######################################################################
# Automatically generated by qmake (3.1) Sat Dec 22 16:39:50 2018
######################################################################

TEMPLATE = app
TARGET = ModelViewer
INCLUDEPATH += .

QT += core gui widgets opengl
win32:QT += winextras

unix {
    INCLUDEPATH += /usr/include/freetype2/
    LIBS += -lfreetype -lassimp
    QMAKE_CXXFLAGS += -fopenmp
    QMAKE_LFLAGS += -fopenmp
}

win32-msvc*{
    INCLUDEPATH += D:\Software\libs\glm
    INCLUDEPATH += D:\Software\libs\freetype-2.5.5-vc14-64\include
    INCLUDEPATH += D:\Software\libs\assimp-5.0.1\include
    LIBS += -L"D:\Software\libs\freetype-2.5.5-vc14-64\lib" -lfreetype
    LIBS += -L"D:\Software\libs\assimp-5.0.1\build\code\Release"  -lassimp-vc142-mt
	QMAKE_CXXFLAGS += /openmp
}

win32-g++{
    INCLUDEPATH += D:\software\libs\glm
    INCLUDEPATH += D:\Software\libs\freetype-2.10.1\include
    INCLUDEPATH += D:\Software\libs\assimp-5.0.1\include
    LIBS += -L"D:\Software\libs\freetype-2.10.1\build" -lfreetype
    LIBS += -L"D:\Software\libs\assimp-5.0.1\build\code" -lassimp -llibzlibstatic -llibIrrXML
}

CONFIG += c++17


CONFIG(release, debug|release) {
    CONFIG -= console
}
CONFIG(debug, debug|release) {
    CONFIG += console
}

win32:RC_ICONS += res\ModelViewer.ico

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += AABB.h \
    AppleSurface.h \
    AssImpMesh.h \
    AssImpMeshExporter.h \
    AssImpModelLoader.h \
    BackgroundColor.h \
    BentHorns.h \
    BoundingBox.h \
    BoundingSphere.h \
    BowTie.h \
    BoySurface.h \
    BreatherSurface.h \
    Cone.h \
    ConeShell.h \
    Crescent.h \
    Cube.h \
    Cylinder.h \
    DoubleCone.h \
    Drawable.h \
    Figure8KleinBottle.h \
    Folium.h \
    GLCamera.h \
    GLMaterial.h \
    GLWidget.h \
    GraysKlein.h \
    GridMesh.h \
    Horn.h \
    IDrawable.h \
    IParametricSurface.h \
    KleinBottle.h \
    LimpetTorus.h \
    MainWindow.h \
    MeshProperties.h \
    ModelObjectList.h \
    ModelViewer.h \
    ParametricSurface.h \
    Periwinkle.h \
    Plane.h \
    Point.h \
    Resource.h \
    SaddleTorus.h \
    Sphere.h \
    SphericalHarmonic.h \
    SpindleShell.h \
    SteinerSurface.h \
    SuperToroid.h \
    SuperEllipsoid.h \
    Spring.h \
    Teapot.h \
    TeapotData.h \
    TextRenderer.h \
    ToolPanel.h \
    TopShell.h \
    Torus.h \
    Triangle.h \
    TriangleBaldwinWeber.h \
    TriangleMesh.h \
    TriangleMollerTrumbore.h \
    TriaxialHexatorus.h \
    TriaxialTritorus.h \
    TwistedPseudoSphere.h \
    TwistedTriaxial.h \
    TurretShell.h \
    VerrillMinimal.h \
    WrinkledPeriwinkle.h \
    ParametricSurface.h \
    SphericalHarmonicsEditor.h \
    ClippingPlanesEditor.h \
    GraysKleinEditor.h \
    SuperToroidEditor.h \
    SuperEllipsoidEditor.h \
    SpringEditor.h \
    mikktspace.h \
    stb_image.h
FORMS += \
    BackgroundColor.ui \
    MainWindow.ui \
    ModelViewer.ui \
    SphericalHarmonicsEditor.ui \
    ClippingPlanesEditor.ui \
    GraysKleinEditor.ui \
    SuperToroidEditor.ui \
    SuperEllipsoidEditor.ui \
    SpringEditor.ui
SOURCES += AppleSurface.cpp \
    AssImpMesh.cpp \
    AssImpMeshExporter.cpp \
    AssImpModelLoader.cpp \
    BackgroundColor.cpp \
    BentHorns.cpp \
    BoundingBox.cpp \
    BoundingSphere.cpp \
    BowTie.cpp \
    BoySurface.cpp \
    BreatherSurface.cpp \
    Cone.cpp \
    ConeShell.cpp \
    Crescent.cpp \
    Cube.cpp \
    Cylinder.cpp \
    DoubleCone.cpp \
    Drawable.cpp \
    Figure8KleinBottle.cpp \
    Folium.cpp \
    GLCamera.cpp \
    GLMaterial.cpp \
    GLWidget.cpp \
    GraysKlein.cpp \
    GridMesh.cpp \
    Horn.cpp \
    KleinBottle.cpp \
    LimpetTorus.cpp \
    MeshProperties.cpp \
    ModelObjectList.cpp \
    ModelViewer.cpp \
    ToolPanel.cpp \
    Triangle.cpp \
    TriangleBaldwinWeber.cpp \
    TriangleMollerTrumbore.cpp \
    main.cpp \
    MainWindow.cpp \
    ParametricSurface.cpp \
    Periwinkle.cpp \
    Plane.cpp \
    Point.cpp \
    SaddleTorus.cpp \
    Sphere.cpp \
    SphericalHarmonic.cpp \
    SpindleShell.cpp \
    SteinerSurface.cpp \
    SuperToroid.cpp \
    SuperEllipsoid.cpp \
    Spring.cpp \
    Teapot.cpp \
    TextRenderer.cpp \
    TopShell.cpp \
    Torus.cpp \
    TriangleMesh.cpp \
    TriaxialHexatorus.cpp \
    TriaxialTritorus.cpp \
    TwistedPseudoSphere.cpp \
    TwistedTriaxial.cpp \
    TurretShell.cpp \
    VerrillMinimal.cpp \
    WrinkledPeriwinkle.cpp \
    SphericalHarmonicsEditor.cpp \
    ClippingPlanesEditor.cpp \
    GraysKleinEditor.cpp \
    SuperToroidEditor.cpp \
    SuperEllipsoidEditor.cpp \
    SpringEditor.cpp \
    mikktspace.c \
    stb_image.cpp

RESOURCES += \
    ModelViewer.qrc

DISTFILES += \
    shaders/background.frag \
    shaders/background.vert \
    shaders/clipping_plane.frag \
    shaders/clipping_plane.vert \
    shaders/clipped_mesh.frag \
    shaders/clipped_mesh.vert \
    shaders/debug_quad.vert \
    shaders/debug_quad_depth.frag \
    shaders/selection.frag \
    shaders/selection.vert \
    shaders/splitScreen.frag \
    shaders/splitScreen.vert \
    shaders/text.vert \
    shaders/text.frag \
    shaders/axis.vert \
    shaders/axis.frag \
    shaders/face_normal.vert \
    shaders/face_normal.geom \
    shaders/face_normal.frag \
    shaders/vertex_normal.vert \
    shaders/vertex_normal.geom \
    shaders/vertex_normal.frag \
    shaders/twoside_per_fragment.vert \
    shaders/twoside_per_fragment.geom \
    shaders/twoside_per_fragment.frag \
    shaders/shadow_mapping_depth.vert \
    shaders/shadow_mapping_depth.frag \
    shaders/skybox.vert \
    shaders/skybox.frag \
    shaders/irradiance_convolution.frag \
    shaders/brdf.vert shaders/brdf.frag \
    shaders/prefilter.frag \
    shaders/light_cube.vert \
    shaders/light_cube.frag
